QST_HOST: ''
QST_HTTP_PORT: 30000
QST_LOG_FILE_PATH: ./current.log
QST_SERVICE_VERSION: 0.1
EXECUTE_AS_DRY_RUN: false
LAUNCHDARKLY_SDK_KEY: ""
LAUNCHDARKLY_OFFLINE: true
LAUNCHDARKLY_LOADDATA_FROM_FILES: ""
MONGODB_ENABLE_DNS_SEEDLIST: true
MONGODB_USERNAME: ""
MONGODB_PASSWORD: ""
MONGODB_HOST: ""
MONGODB_PARAMETER: ""
MONGODB_NAME: ""
MONGODB_AUTH_MECHANISM: ""
MONGODB_SOCKS5_PROXY: ""
AWS_ROLE_ARN: ""
AWS_SESSION_NAME: ""
AWS_REGION: ""
AWS_WEB_IDENTITY_TOKEN_FILE: ""