// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package models

import (
	"time"

	externalRef0 "github.azc.ext.hp.com/3DSoftware/go-gravity-api/api/base/models"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorType.
const (
	DependencyError  ErrorType = "DependencyError"
	InvalidParameter ErrorType = "InvalidParameter"
	MissingParameter ErrorType = "MissingParameter"
)

// Defines values for GetHelloWorldsParamsAccept.
const (
	ApplicationvndApiJson            GetHelloWorldsParamsAccept = "application/vnd.api+json"
	ApplicationvndApiJsonCharsetUtf8 GetHelloWorldsParamsAccept = "application/vnd.api+json; charset=utf-8"
)

// AuditStamp defines model for AuditStamp.
type AuditStamp struct {
	CreatedBy *Relationship `json:"createdBy,omitempty"`
	UpdatedBy *Relationship `json:"updatedBy,omitempty"`
}

// DateStamp defines model for DateStamp.
type DateStamp struct {
	CreatedAt time.Time  `json:"createdAt"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// Dependencies defines model for Dependencies.
type Dependencies map[string]bool

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`

	// Type An internal error code to further specify what caused an error.
	Type *ErrorType `json:"type,omitempty"`
}

// ErrorType An internal error code to further specify what caused an error.
type ErrorType string

// Health A structure to represent health check responses in HTTP calls
type Health struct {
	// Dependencies lists components or services that are critical for the responder to work properly
	Dependencies *map[string]bool `json:"dependencies,omitempty"`

	// Healthy Whether the responder is healthy or not
	Healthy bool `json:"healthy"`

	// Versions list relevant components and their deployed versions
	// (as in, build system defined versions)
	Versions *map[string]string `json:"versions,omitempty"`
}

// HelloWorld defines model for HelloWorld.
type HelloWorld struct {
	Attributes HelloWorldAttributes `json:"attributes"`
	Id         UUID                 `json:"id"`
	Type       string               `json:"type"`
}

// HelloWorldAttributes defines model for HelloWorldAttributes.
type HelloWorldAttributes struct {
	CreatedAt time.Time  `json:"createdAt"`
	Message   string     `json:"message"`
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// HelloWorldRelationships defines model for HelloWorldRelationships.
type HelloWorldRelationships = AuditStamp

// JSONAPI defines model for JSONAPI.
type JSONAPI struct {
	Version string `json:"version"`
}

// JSONAPIError defines model for JSONAPIError.
type JSONAPIError struct {
	Errors *[]JSONAPIErrorElement `json:"errors,omitempty"`
}

// JSONAPIErrorElement defines model for JSONAPIErrorElement.
type JSONAPIErrorElement struct {
	Code   *int       `json:"code,omitempty"`
	Detail *string    `json:"detail,omitempty"`
	Id     *UUID      `json:"id,omitempty"`
	Links  *Links     `json:"links,omitempty"`
	Meta   *MetaError `json:"meta,omitempty"`
	Source *struct {
		Pointer *string `json:"pointer,omitempty"`
	} `json:"source,omitempty"`
	Status *int    `json:"status,omitempty"`
	Title  *string `json:"title,omitempty"`
}

// Links defines model for Links.
type Links struct {
	Self URL `json:"self"`
}

// LinksRelationship defines model for LinksRelationship.
type LinksRelationship struct {
	Related URL `json:"related"`
	Self    URL `json:"self"`
}

// Liveness Liveness send information about backend state and version
type Liveness struct {
	Healthy  bool      `json:"healthy"`
	Versions *Versions `json:"versions,omitempty"`
}

// Meta defines model for Meta.
type Meta = map[string]interface{}

// MetaError defines model for MetaError.
type MetaError struct {
	Count  *int `json:"count,omitempty"`
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
	Total  *int `json:"total,omitempty"`
}

// POSTHelloWorldAttributes defines model for POSTHelloWorldAttributes.
type POSTHelloWorldAttributes struct {
	Message *string `json:"message,omitempty"`
}

// Relationship defines model for Relationship.
type Relationship struct {
	Data  *ResourceData      `json:"data,omitempty"`
	Links *LinksRelationship `json:"links,omitempty"`
}

// ResourceData defines model for ResourceData.
type ResourceData struct {
	Id   UUID   `json:"id"`
	Type string `json:"type"`
}

// ResourceResponseDocument defines model for ResourceResponseDocument.
type ResourceResponseDocument struct {
	Jsonapi JSONAPI `json:"jsonapi"`
	Links   *Links  `json:"links,omitempty"`
	Meta    *Meta   `json:"meta,omitempty"`
}

// URL defines model for URL.
type URL = string

// UUID defines model for UUID.
type UUID = openapi_types.UUID

// Versions defines model for Versions.
type Versions map[string]string

// InternalServerError defines model for InternalServerError.
type InternalServerError = Error

// LivenessResponse A structure to represent health check responses in HTTP calls
type LivenessResponse = Health

// ReadinessResponse A structure to represent health check responses in HTTP calls
type ReadinessResponse = Health

// HelloworldParams defines parameters for Helloworld.
type HelloworldParams struct {
	// Name Name to salute
	Name *string `form:"name,omitempty" json:"name,omitempty"`
}

// GetHelloWorldsParams defines parameters for GetHelloWorlds.
type GetHelloWorldsParams struct {
	Accept         externalRef0.Accept          `json:"Accept"`
	AcceptEncoding *externalRef0.AcceptEncoding `json:"Accept-Encoding,omitempty"`
	Authorization  externalRef0.Authorization   `json:"Authorization"`
	XRequestID     *externalRef0.XRequestID     `json:"X-Request-ID,omitempty"`
}

// GetHelloWorldsParamsAccept defines parameters for GetHelloWorlds.
type GetHelloWorldsParamsAccept string

// CreateHelloWorldApplicationVndAPIPlusJSONBody defines parameters for CreateHelloWorld.
type CreateHelloWorldApplicationVndAPIPlusJSONBody struct {
	Data *struct {
		Attributes *POSTHelloWorldAttributes `json:"attributes,omitempty"`
		Type       *string                   `json:"type,omitempty"`
	} `json:"data,omitempty"`
}

// LivenessParams defines parameters for Liveness.
type LivenessParams struct {
	XRequestID *externalRef0.XRequestID `json:"X-Request-ID,omitempty"`
}

// ReadinessParams defines parameters for Readiness.
type ReadinessParams struct {
	XRequestID *externalRef0.XRequestID `json:"X-Request-ID,omitempty"`
}

// CreateHelloWorldApplicationVndAPIPlusJSONRequestBody defines body for CreateHelloWorld for application/vnd.api+json ContentType.
type CreateHelloWorldApplicationVndAPIPlusJSONRequestBody CreateHelloWorldApplicationVndAPIPlusJSONBody
